export const APP_NAME = "Noc Noc"
export var access_token = null
export var first_name = null
export var last_name = null
export var email = null
export var password = null
export var cell_phone = null
export var status = null
export var avatar = null