export const APP_NAME = "NOC NOC"
export var access_token = ''
export var first_name = null
export var last_name = null
export var email = null
export var password = null
export var cell_phone = null
export var status = null
export var avatar = null
export var birthday = null
export var id = null